version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: taskmanager-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pratik@25  
      MYSQL_DATABASE: task_manager_db
    ports:
      - "4306:3306"  # changed host port to avoid conflict
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: taskmanager-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306        # this stays 3306 (internal container port)
      DB_USERNAME: root
      DB_PASSWORD: Pratik@25
      DB_NAME: task_manager_db
      JWT_SECRET: pppratik
    depends_on:
      - db

volumes:
  mysql_data:
